main = ".open-next/worker.js"
name = "clockify-manager"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_APP_NAME = "Clockify Manager"
NEXT_PUBLIC_API_URL = "https://clockify-manager.quuantum.com"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"